Update requirements.txt
Error while building images : Error: No such command 'image'.
error: build error: building at STEP "RUN /tmp/scripts/assemble": while running runtime: exit status 2

For that new changes in requirements.txt file